// Generated by https://quicktype.io

export interface RecipeByCuisine {
    results:      Result[];
    offset:       number;
    number:       number;
    totalResults: number;
}

export interface Result {
    id:        number;
    title:     string;
    image:     string;
    imageType: string;
}
